# Generated by Django 4.1.3 on 2022-11-17 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('WorkLocation', models.CharField(choices=[('Remote', 'Remote'), ('In Office', 'In Office')], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('minSalary', models.CharField(max_length=50)),
                ('maxSalary', models.CharField(max_length=50)),
                ('incentive', models.CharField(max_length=50)),
                ('workExMin', models.CharField(max_length=50)),
                ('workExMax', models.CharField(max_length=50)),
                ('vacancy', models.CharField(max_length=50)),
                ('jobDesc', models.CharField(max_length=300)),
            ],
        ),
    ]
