# Generated by Django 4.1.3 on 2022-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0002_alter_jobdiscription_jobdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdiscription',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
