# Generated by Django 4.1.1 on 2022-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0003_alter_jobdiscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdiscription',
            name='incentive',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdiscription',
            name='maxSalary',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdiscription',
            name='minSalary',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdiscription',
            name='workExMax',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='jobdiscription',
            name='workExMin',
            field=models.IntegerField(max_length=2),
        ),
    ]
